// apps/react-ui/src/layout/Layout.tsx
import { useEffect } from 'react';
import { NavLink, Outlet, useNavigate } from 'react-router-dom';
import { NAV_ITEMS } from '@iota/content';

/**
 * Shared page chrome: nav bar (driven by @iota/content's NAV_ITEMS, the
 * single source of truth also used by the Angular router/nav) plus the
 * routed page content. Also mounts the embedded <iota-terminal> panel and
 * bridges its `iota-terminal:navigate` CustomEvent to React Router, since
 * the terminal is a framework-agnostic Custom Element that can't call
 * useNavigate() directly.
 */
export default function Layout() {
  const navigate = useNavigate();

  useEffect(() => {
    const handleNavigate = (event: Event) => {
      const path = (event as CustomEvent<{ path: string }>).detail?.path;
      if (path) navigate(path);
    };
    document.addEventListener('iota-terminal:navigate', handleNavigate);
    return () => document.removeEventListener('iota-terminal:navigate', handleNavigate);
  }, [navigate]);

  return (
    <div className="min-h-screen flex flex-col gap-6 p-4 md:p-8 max-w-3xl mx-auto">
      <header className="flex flex-col gap-3">
        <h1 className="text-2xl">
          iota-terminal <iota-cursor></iota-cursor>
        </h1>
        <nav className="flex flex-wrap gap-x-4 gap-y-2 text-sm">
          {NAV_ITEMS.map((item) => (
            <NavLink
              key={item.id}
              to={`/${item.path}`}
              end={item.path === ''}
              className={({ isActive }) =>
                isActive ? 'text-terminal-fg underline' : 'text-terminal-dim hover:text-terminal-fg'
              }
            >
              {item.label}
            </NavLink>
          ))}
        </nav>
      </header>
      <main className="flex-1">
        <Outlet />
      </main>
      <iota-terminal></iota-terminal>
    </div>
  );
}

// apps/angular-ui/src/layout/layout.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, OnDestroy, OnInit } from '@angular/core';
import { Router, RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { NAV_ITEMS } from '@iota/content';

/**
 * Shared page chrome: nav bar (driven by @iota/content's NAV_ITEMS, the
 * single source of truth also used by the React nav/router) plus the
 * routed page content. Also mounts the embedded <iota-terminal> panel and
 * bridges its `iota-terminal:navigate` CustomEvent to the Angular Router,
 * since the terminal is a framework-agnostic Custom Element that can't
 * call Router.navigateByUrl() directly.
 */
@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [RouterLink, RouterLinkActive, RouterOutlet],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './layout.component.html'
})
export class LayoutComponent implements OnInit, OnDestroy {
  navItems = NAV_ITEMS;

  constructor(private router: Router) {}

  private readonly handleNavigate = (event: Event) => {
    const path = (event as CustomEvent<{ path: string }>).detail?.path;
    if (path) this.router.navigateByUrl(path);
  };

  ngOnInit(): void {
    document.addEventListener('iota-terminal:navigate', this.handleNavigate);
  }

  ngOnDestroy(): void {
    document.removeEventListener('iota-terminal:navigate', this.handleNavigate);
  }
}

<div class="min-h-screen flex flex-col gap-6 p-4 md:p-8 max-w-3xl mx-auto">
  <header class="flex flex-col gap-3">
    <h1 class="text-2xl">iota-terminal <iota-cursor></iota-cursor></h1>
    <nav class="flex flex-wrap gap-x-4 gap-y-2 text-sm">
      @for (item of navItems; track item.id) {
        <a
          [routerLink]="'/' + item.path"
          routerLinkActive
          #rla="routerLinkActive"
          [routerLinkActiveOptions]="{ exact: item.path === '' }"
          [class]="
            rla.isActive ? 'text-terminal-fg underline' : 'text-terminal-dim hover:text-terminal-fg'
          "
          >{{ item.label }}</a
        >
      }
    </nav>
  </header>
  <main class="flex-1">
    <router-outlet></router-outlet>
  </main>
  <iota-terminal></iota-terminal>
</div>
