// apps/angular-ui/src/pages/not-found/not-found.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-not-found',
  standalone: true,
  imports: [RouterLink],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <iota-window title="404">
      <p>command not found: {{ path }}</p>
      <p class="mt-2"><a routerLink="/" class="underline">cd ~</a></p>
    </iota-window>
  `
})
export class NotFoundComponent {
  path = window.location.pathname;
}

<iota-window title="404">
  <p>command not found: {{ path }}</p>
  <p class="mt-2"><a routerLink="/" class="underline">cd ~</a></p>
</iota-window>

// apps/react-ui/src/pages/NotFound.tsx
import { Link } from 'react-router-dom';

export default function NotFound() {
  return (
    <iota-window title="404">
      <p>command not found: {window.location.pathname}</p>
      <p className="mt-2">
        <Link to="/" className="underline">
          cd ~
        </Link>
      </p>
    </iota-window>
  );
}
