// apps/react-ui/src/pages/AboutSite.tsx
import { ABOUT_SITE } from '@iota/content';

export default function AboutSite() {
  return (
    <iota-window title="~/site.md">
      <div className="flex flex-col gap-4">
        {ABOUT_SITE.paragraphs.map((paragraph, i) => (
          <p key={i}>{paragraph}</p>
        ))}
      </div>
    </iota-window>
  );
}

// apps/angular-ui/src/pages/about-site/about-site.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { ABOUT_SITE } from '@iota/content';

@Component({
  selector: 'app-about-site',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <iota-window title="~/site.md">
      <div class="flex flex-col gap-4">
        @for (paragraph of paragraphs; track $index) {
          <p>{{ paragraph }}</p>
        }
      </div>
    </iota-window>
  `
})
export class AboutSiteComponent {
  paragraphs = ABOUT_SITE.paragraphs;
}

<iota-window title="~/site.md">
  <div class="flex flex-col gap-4">
    @for (paragraph of paragraphs; track $index) {
      <p>{{ paragraph }}</p>
    }
  </div>
</iota-window>
