// apps/react-ui/src/pages/Projects.tsx
import { PROJECTS } from '@iota/content';

export default function Projects() {
  return (
    <iota-window title="~/projects">
      <ul className="flex flex-col gap-6">
        {PROJECTS.map((project) => (
          <li key={project.id} className="flex flex-col gap-1">
            <h2 className="text-lg text-terminal-fg">{project.title}</h2>
            <p>{project.description}</p>
            <p className="text-sm text-terminal-dim">{project.technologies.join(' · ')}</p>
            <div className="flex gap-4 text-sm">
              <a href={project.githubUrl} className="underline" target="_blank" rel="noreferrer">
                source
              </a>
              {project.liveUrl && (
                <a href={project.liveUrl} className="underline" target="_blank" rel="noreferrer">
                  live
                </a>
              )}
            </div>
          </li>
        ))}
      </ul>
    </iota-window>
  );
}

// apps/angular-ui/src/pages/projects/projects.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { PROJECTS } from '@iota/content';

@Component({
  selector: 'app-projects',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <iota-window title="~/projects">
      <ul class="flex flex-col gap-6">
        @for (project of projects; track project.id) {
          <li class="flex flex-col gap-1">
            <h2 class="text-lg text-terminal-fg">{{ project.title }}</h2>
            <p>{{ project.description }}</p>
            <p class="text-sm text-terminal-dim">{{ project.technologies.join(' · ') }}</p>
            <div class="flex gap-4 text-sm">
              <a [href]="project.githubUrl" class="underline" target="_blank" rel="noreferrer">source</a>
              @if (project.liveUrl) {
                <a [href]="project.liveUrl" class="underline" target="_blank" rel="noreferrer">live</a>
              }
            </div>
          </li>
        }
      </ul>
    </iota-window>
  `
})
export class ProjectsComponent {
  projects = PROJECTS;
}

<iota-window title="~/projects">
  <ul class="flex flex-col gap-6">
    @for (project of projects; track project.id) {
      <li class="flex flex-col gap-1">
        <h2 class="text-lg text-terminal-fg">{{ project.title }}</h2>
        <p>{{ project.description }}</p>
        <p class="text-sm text-terminal-dim">{{ project.technologies.join(' · ') }}</p>
        <div class="flex gap-4 text-sm">
          <a [href]="project.githubUrl" class="underline" target="_blank" rel="noreferrer"
            >source</a
          >
          @if (project.liveUrl) {
            <a [href]="project.liveUrl" class="underline" target="_blank" rel="noreferrer">live</a>
          }
        </div>
      </li>
    }
  </ul>
</iota-window>
